# Generated by Django 4.1.1 on 2022-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_customer_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searc_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
